from distutils.core import setup
from setuptools import find_packages

setup(
    name='autokeras',
    packages=find_packages(exclude=('tests',)),
    install_requires=['scipy',
                      'torch==1.0.0',
                      'torchvision==0.2.1',
                      'numpy',
                      'keras==2.2.4',
                      'scikit-learn',
                      'scikit-image',
                      'tqdm',
                      'tensorflow==1.12.0',
                      'imageio',
                      'requests',
                      'lightgbm',
                      'pandas',
                      'librosa',
                      'numba',
                      'inflect',
                      'unidecode',
                      'nltk',
                      'lws',
                      #'opencv-python==4.0.0.21',
                      'boto3'],
    version='0.3.6',
    description='AutoML for deep learning',
    author='DATA Lab at Texas A&M University',
    author_email='jhfjhfj1@gmail.com',
    url='http://autokeras.com',
    download_url='https://github.com/jhfjhfj1/autokeras/archive/0.3.6.tar.gz',
    keywords=['AutoML', 'keras'],
    classifiers=[]
)
